baseURL = ""

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "DataRookies Learning Portal Website"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = "Website version of the DataRookies Learning Portal"
    github_repository = "https://github.com/DataRookies/DataRookiesLearningPortal"
    # version = "0.2.1"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/DataRookies/DataRookiesLearningPortal"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archives", "blog", "entry", "post", "posts"]


# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Facebook"
    url = "https://fb.com/datarookies"
    weight = 2

[[menu.main]]
    name = "Join Our Slack Channel!"
    url = "https://tinyurl.com/joinDataRookies"
    weight = 2
